Specify amount and currencies to convert:

<form action="<?php echo $this->getFormAction() ?>" method="post">
  <?php echo $this->getBlockHtml('formkey'); ?>
Amount: <input type="text" name="amount" /> <br />
  From: <select name="from"> 
  <?php foreach ($this->getCurrencies() as $currencyCode): ?>
     <option value="<?php echo $currencyCode ?>"><?php echo $currencyCode ?></option>
  <?php endforeach; ?>
  </select> <br />
  To: <select name="to"> 
  <?php foreach ($this->getCurrencies() as $currencyCode): ?>
     <option value="<?php echo $currencyCode ?>"><?php echo $currencyCode ?></option>
  <?php endforeach; ?>
  </select>

<input type="submit" />
</form>